import Notification from '@/comps/Notification'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/comps/Navbar'
import Footer from '@/comps/Footer'
import Authprovider from '@/comps/AuthProvider/Authprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
        <Notification/>
        <Navbar/>
        <Authprovider>
        {children}
        </Authprovider>
        <Footer/>
       
        </body>
    </html>
  )
}
